### ISSUE TITLE
ModuleNotFoundError: import of numba.core.typing halted; None ine 61, in _typeof_bmba-0.55.1-py3.9-win-amd64.egg\numba\core\typing\typeof.py", line 61, in _typeo in sys.modules

### ISSUE THREAD

**Issue by doggie007** [mortacious/numba-kdtree#5] opened 2022-04-09 22:24 UTC
When I run the line 
`indices = kdtree.query_radius(data[:100], r=0.5, return_sorted=True)`
in your example code, it raises an error:

> lib\site-packages\numba-0.55.1-py3.9-win-amd64.egg\numba\core\dispatcher.py", line 733, in typeof_pyval
  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\site-packages\numba-0.55.1-py3.9-win-amd64.egg\numba\core\typing\typeof.py", line 31, in typeof  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\site-packages\numba-0.55.1-py3.9-win-amd64.egg\numba\core\typing\typeof.py", line 44, in typeof_impl
  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\site-packages\numba-0.55.1-py3.9-win-amd64.egg\numba\core\typing\typeof.py", line 61, in _typeof_buffer
ModuleNotFoundError: import of numba.core.typing halted; None in sys.modules

**Comment by mortacious** [comment] 2022-04-10 12:05
I was able to reproduce your problem, but for me it happened in the `__del__` function of the `KDTree` class at the end of the script. 
The cause for the problem is most probably that the interpeter is already in the finalize state there and imports or compilation of numba code is no longer possible. However, in this case it is necessary in order to release the C resources of the KDTree. 
I just pushed a fix in the branch `bugfix/free_on_finalize`. Does the change work for you?

**Closed** 2022-12-11 05:34 UTC
